language: python
python:
  - "3.9"
install:
  - pip install pep8
  - pip install pylint
script:
  - pep8 --ignore=E402 .
  - pylint resources/lib
  - cd resources/lib
  - python -m unittest discover -v